export const CHANGE_SEARCH_TEXT = "CHANGE_SEARCH_TEXT";
export const FETCH_ROBOTS_PENDING = "FETCH_ROBOTS_PENDING";
export const FETCH_ROBOTS_SUCCESS = "FETCH_ROBOTS_SUCCESS";
export const FETCH_ROBOTS_FAILED = "FETCH_ROBOTS_FAILED";
